name: go2_rl_ws_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.8.1
  - numpy=1.21
  - pandas=1.3
  - scipy=1.7
  - matplotlib=3.4
  - opencv=4.5
  - pip
  - pip:
    - onnxruntime-gpu
    


